### ISSUE TITLE
sql issue

### ISSUE THREAD

**Issue by R1NTS1** [KalobMTaulien/PHP-Login-System#1]
ALTER TABLE `users`
  ADD UNIQUE KEY `email` (`email`)

#1071 - Specified key was too long; max key length is 767 bytes

how i can fix this?

**Comment by Akiraff2015** [comment]
Please ensure to Google before asking unnecessary questions. This was the [first result of the search](https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes).
