### ISSUE TITLE
Could not connect to database.

### ISSUE THREAD

**Issue by SedatOzdemir** [KalobMTaulien/PHP-Login-System#3]
If I change the database connection password, I see "Could not connect to database" message. But I checked all settings, it had to work. Also I have a login_course database and I imported the .sql file.

new PDO( 'mysql:charset=utf8mb4;host=localhost;port=3306;dbname=login_course', 'root', 'HERE' );

How can I solve it?

**Comment by KalobTaulien** [comment]
You'll ned to update the root users password. Using root was just the example in this course (and repo), you really shouldn't use root user in general. 

Try opening your phpMyAdmin, creating a new user (you'll need to grant it access to your login_course database, and give it the appropriate permissions (UPDATE, INSERT, etc.)). Once you create this new user, use:

```new PDO( 'mysql:charset=utf8mb4;host=localhost;port=3306;dbname=login_course', 'new_user', 'your_new_password' );```
